import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";
import Scripts from "@/components/Scripts";
const inter = Inter({ subsets: ["latin"] });
import TestimonialsCarousel from "@/components/TestimonialsCarousel"
export default function Home() {
  return (
    <>
      <Head>
        <title>Mishael</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/images/Mishael.png" />
      </Head>
      <main>
        <>
          {/* End Preloader */}
          <div className="page-wrapper">
            {/* Start sidebar widget content */}
            <div className="xs-sidebar-group info-group info-sidebar">
              <div className="xs-overlay xs-bg-black" />
              <div className="xs-sidebar-widget">
                <div className="sidebar-widget-container">
                  <div className="widget-heading">
                    <a href="#" className="close-side-widget">
                      X
                    </a>
                  </div>
                  <div className="sidebar-textwidget">
                    <div className="sidebar-info-contents">
                      <div className="content-inner">
                        <div className="logo">
                          <a href="index.html">
                            <img
                              src="assets/images/Mishael.png"
                              alt=""
                            />
                          </a>
                        </div>
                        <div className="content-box">
                          <h4>About Us</h4>
                          <div className="inner-text">
                            <p>
                              Contrary to popular belief, Lorem Ipsum is not
                              simply random text. It has roots in a piece of
                              classical Latin literature from 45 BC, making it
                              over 2000 years old.
                            </p>
                          </div>
                        </div>
                        <div className="form-inner">
                          <h4>Get a free quote</h4>
                          <form action="index.html" method="post">
                            <div className="form-group">
                              <input
                                type="text"
                                name="name"
                                placeholder="Name"
                                required=""
                              />
                            </div>
                            <div className="form-group">
                              <input
                                type="email"
                                name="email"
                                placeholder="Email"
                                required=""
                              />
                            </div>
                            <div className="form-group">
                              <textarea
                                name="message"
                                placeholder="Message..."
                                defaultValue={""}
                              />
                            </div>
                            <div className="form-group message-btn">
                              <button
                                className="thm-btn"
                                type="submit"
                                data-loading-text="Please wait..."
                              >
                                <span className="txt">Submit Now</span>
                                <span className="bdrl" />
                                <span className="bdrr" />
                              </button>
                            </div>
                          </form>
                        </div>
                        <div className="sidebar-contact-info">
                          <h4>Contact Info</h4>
                          <ul>
                            <li>
                              <span className="icon-placeholder-1" /> 88 broklyn
                              street, New York
                            </li>
                            <li>
                              <span className="icon-phone-ringing" />
                              <a href="tel:123456789">+1 555-9990-153</a>
                            </li>
                            <li>
                              <span className="fa fa-envelope" />
                              <a href="mailto:info@example.com">
                                info@example.com
                              </a>
                            </li>
                          </ul>
                        </div>
                        <div className="thm-social-link1">
                          <ul className="social-box">
                            <li className="facebook">
                              <a href="#">
                                <i
                                  className="icon-facebook"
                                  aria-hidden="true"
                                />
                              </a>
                            </li>
                            <li className="twitter">
                              <a href="#">
                                <i
                                  className="icon-twitter"
                                  aria-hidden="true"
                                />
                              </a>
                            </li>
                            <li className="linkedin">
                              <a href="#">
                                <i
                                  className="icon-instagram"
                                  aria-hidden="true"
                                />
                              </a>
                            </li>
                            <li className="gplus">
                              <a href="#">
                                <i
                                  className="icon-pinterest"
                                  aria-hidden="true"
                                />
                              </a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* End sidebar widget content */}
            {/*Start Main Header One*/}
            <header className="main-header main-header-two">
              <div className="main-header-two__inner">
                <nav className="main-menu main-menu-one">
                  <div className="main-menu__wrapper clearfix">
                    <div className="auto-container">
                      <div className="main-menu__wrapper-inner">
                        <div className="main-header-two__left">
                          <div className="logo-box-one">
                            <a href="index.html">
                              <img
                                src="assets/images/Mishael.png"
                                alt="Awesome Logo"
                                title=""
                              />
                            </a>
                          </div>
                        </div>
                        <div className="main-menu-box">
                          <a href="#" className="mobile-nav__toggler">
                            <i className="fa fa-bars" />
                          </a>
                          <ul className="main-menu__list">
                            <li>
                              <a href="index.html">Home</a>
                            </li>

                            <li>
                              <a href="about.html">About</a>
                            </li>
                            <li>
                              <a href="about.html">Products</a>
                            </li>
                            <li>
                              <a href="contact.html">Contact</a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </nav>
              </div>
            </header>

            {/*End Main Header One*/}
            <div className="stricky-header stricky-header--one stricked-menu main-menu">
              <div className="sticky-header__content" />
              {/* /.sticky-header__content */}
            </div>
            {/* /.stricky-header */}
            {/*Start Main Slider */}
            <section className="main-slider main-slider-one">
              <div className="swiper-container main-slider-one__carousel">
                <div className="swiper-wrapper">
                  {/*Start Main Slider One*/}
                  <div className="swiper-slide">
                    <div
                      className="image-layer"
                      style={{
                        backgroundImage:
                          "url(assets/images/slides/slider-v1-bg.jpg)",
                      }}
                    ></div>
                    <div className="auto-container">
                      <div className="main-slider-one__single">
                        <div className="main-slider-one__img">
                          <img
                            src="assets/images/slider-v1-img1.jpg.png"
                            alt="#"
                          />
                        </div>
                        <div className="main-slider-one__content">
                          {/*<ul className="social-links">
                        <li>
                          <a href="#">Fb.</a>
                        </li>
                        <li>
                          <a href="#">Tw.</a>
                        </li>
                        <li>
                          <a href="#">In.</a>
                        </li>
                        <li>
                          <a href="#">Be.</a>
                        </li>
                      </ul>*/}
                          <div className="title">
                            <h2>
                              Sustainable <br />
                              Style <br />
                              Everyday
                            </h2>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/*End Main Slider One*/}
                  {/*Start Main Slider One*/}
                  <div className="swiper-slide">
                    <div
                      className="image-layer"
                      style={{
                        backgroundImage:
                          "url(assets/images/slides/slider-v1-bg.jpg)",
                      }}
                    ></div>
                    <div className="auto-container">
                      <div className="main-slider-one__single">
                        <div className="main-slider-one__img">
                          <img
                            src="assets/images/slider-v1-img1.jpg.png"
                            alt="#"
                          />
                        </div>
                        <div className="main-slider-one__content">
                          {/* <ul className="social-links">
                        <li>
                          <a href="#">Fb.</a>
                        </li>
                        <li>
                          <a href="#">Tw.</a>
                        </li>
                        <li>
                          <a href="#">In.</a>
                        </li>
                        <li>
                          <a href="#">Be.</a>
                        </li>
                      </ul>*/}
                          <div className="title">
                            <h2>
                              Sustainable <br />
                              Style <br />
                              Everyday
                            </h2>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/*End Main Slider One*/}

                  {/*End Main Slider One*/}
                  {/*Start Main Slider One*/}

                  {/*End Main Slider One*/}
                </div>
                {/* <div className="project-one__control-wrap">
              <div className="swiper-counter">
                <div id="current2">01</div>
                <div id="total2" />
              </div>
            </div>
            <div className="scroll-pagination">
              <div className="swiper-pagination" />
            </div>*/}
              </div>
            </section>
            {/*End Main Slider*/}
            {/*Start Brand One */}
            <section className="brand-one">
              <div className="auto-container">
                <div className="brand-one__inner">
                  <ul>
                    <li>
                      {/*<a href="#">
                    
                      <img src="assets/images/Mas AI File-01 (1) 1 (1).png" alt="Brand Logo" className="logo-text" />*/}

                      <a href="#">
                        <h1 className="logo-text">MAS</h1>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <h1 className="logo-text">Sauve</h1>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <h1 className="logo-text">Delmas</h1>
                        {/* <img src="assets/images/brand/brand-1-5.png" alt="#" />*/}
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </section>
            {/*End Brand One */}
            {/*Start About One */}
            <section className="about-one">
              <div
                className="big-title1 wow slideInLeft"
                data-wow-delay="500ms"
                data-wow-duration="2500ms"
              >
                <h2>About</h2>
              </div>
              <div
                className="big-title2 wow slideInRight"
                data-wow-delay="500ms"
                data-wow-duration="2500ms"
              >
                <h2>Creative</h2>
              </div>
              <div className="container">
                <div className="about-one__inner">
                  <div className="sec-title text-center tg-heading-subheading animation-style2">
                    <div className="sec-title__tagline">
                      <p className="tg-element-title">about us</p>
                      <div className="border-box" />
                    </div>
                    <h2 className="sec-title__title tg-element-title">
                      Empowering Global Fashion <br />
                      with
                      <br /> Ethical Excellence
                    </h2>
                  </div>
                  {/* <div className="btn-box">
                <a className="thm-btn" href="contact.html">
                  <span className="txt">Explore More</span>
                  <span className="bdrl" />
                  <span className="bdrr" />
                </a>
              </div>*/}
                </div>
              </div>
            </section>
            {/*End About One */}
            {/*Start Advantages One */}
            <section className="advantages-one">
              <div className="container">
                <div className="advantages-one__inner">
                  <ul className="row">
                    <li className="col-xl-4">
                      <div className="advantages-one__single">
                        <div className="advantages-one__single-img">
                          <div className="btn-box">
                            <a href="#">Show all More</a>
                            <div className="border-box" />
                          </div>
                          <div className="inner">
                            <img src="assets/images/Container.png" alt="#" />
                          </div>
                        </div>
                      </div>
                    </li>
                    <li className="col-xl-6">
                      <div className="advantages-one__single">
                        <div className="advantages-one__single-content">
                          <div className="tagline">
                            <a href="#">advantages</a>
                            <div className="border-box" />
                          </div>
                          <div className="title-box">
                            <h2>
                              Design <br />
                              <span>Creatively</span> <br />
                              Beauty
                            </h2>
                          </div>
                          <p>
                            With decades of experience in the RMG industry,
                            Mishael International Inc. has built a reputation
                            for excellence. We are dedicated to providing our
                            clients with the best products at competitive
                            prices, all while maintaining the highest standards
                            of ethical sourcing.
                          </p>
                          {/* <div className="btn-box">
                        <a className="thm-btn" href="contact.html">
                          <span className="txt">View More</span>
                          <span className="bdrl" />
                          <span className="bdrr" />
                        </a>
                      </div>*/}
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </section>
            {/*End Advantages One */}
            {/*Start Counter One */}
            <section className="counter-one">
              {/*  <div className="big-title">
                <h2>Counters</h2>
              </div>*/}
              <div className="auto-container">
                <div className="row">
                  {/*Start Counter One Single*/}
                  <div className="col-xl-3 col-lg-6 col-md-6">
                    <div className="counter-one__single">
                      <div
                        className="border-box wow animated fadeInLeft"
                        data-wow-delay="0.1s"
                      />
                      <div
                        className="counter-one__content wow animated fadeInRight"
                        data-wow-delay="0.1s"
                      >
                        <h2>
                          <span className="odometer" data-count={20}>
                            00
                          </span>{" "}
                          <span className="k">+</span>{" "}
                        </h2>
                        <p>Years Experience</p>
                      </div>
                    </div>
                  </div>
                  {/*End Counter One Single*/}
                  {/*Start Counter One Single*/}
                  <div className="col-xl-3 col-lg-6 col-md-6">
                    <div className="counter-one__single">
                      <div
                        className="border-box wow animated fadeInLeft"
                        data-wow-delay="0.1s"
                      />
                      <div
                        className="counter-one__content wow animated fadeInRight"
                        data-wow-delay="0.1s"
                      >
                        <h2>
                          <span className="odometer" data-count={600}>
                            00
                          </span>{" "}
                          <span className="k">+</span>{" "}
                        </h2>
                        <p>Outlets</p>
                      </div>
                    </div>
                  </div>
                  {/*End Counter One Single*/}
                  {/*Start Counter One Single*/}
                  <div className="col-xl-3 col-lg-6 col-md-6">
                    <div className="counter-one__single">
                      <div
                        className="border-box wow animated fadeInLeft"
                        data-wow-delay="0.1s"
                      />
                      <div
                        className="counter-one__content wow animated fadeInRight"
                        data-wow-delay="0.1s"
                      >
                        <h2>
                          <span className="odometer" data-count={100}>
                            00
                          </span>{" "}
                          <span className="k">+</span>{" "}
                        </h2>
                        <p>Product Variations</p>
                      </div>
                    </div>
                  </div>
                  {/*End Counter One Single*/}
                  {/*Start Counter One Single*/}
                  <div className="col-xl-3 col-lg-6 col-md-6">
                    <div className="counter-one__single">
                      <div
                        className="border-box wow animated fadeInLeft"
                        data-wow-delay="0.1s"
                      />
                      <div
                        className="counter-one__content wow animated fadeInRight"
                        data-wow-delay="0.1s"
                      >
                        <h2>
                          <span className="odometer" data-count={12}>
                            00
                          </span>{" "}
                          <span className="k">k</span>{" "}
                        </h2>
                        <p>Customers Served</p>
                      </div>
                    </div>
                  </div>
                  {/*End Counter One Single*/}
                </div>
              </div>
            </section>
            {/*End Counter One */}
            {/*Start Services One */}
            <section className="services-one">
              <div className="container">
                <div className="row">
                  {/*Start Services One Left Content*/}
                  <div className="col-xl-5">
                    <div className="services-one__left-content">
                      <div className="sec-title tg-heading-subheading animation-style2">
                        <div className="sec-title__tagline">
                          <p className="tg-element-title">what we do</p>
                          <div className="border-box" />
                        </div>
                        <h2 className="sec-title__title tg-element-title">
                          Crafting a Legacy
                          <br /> of Quality and
                          <br /> Trust
                        </h2>
                      </div>
                      <div className="services-one__left-content-text">
                        <p>
                          Our extensive industry network and active involvement
                          in the RMG owners’ association in Bangladesh allow us
                          to stay ahead of trends and deliver exceptional value
                          to our customers.
                        </p>
                      </div>
                    </div>
                  </div>
                  {/*End Services One Left Content*/}
                  {/*Start Services One Right Content*/}
                  <div className="col-xl-7">
                    <div className="services-one__right-content">
                      <ul>
                        <li
                          className="wow animated fadeInRight"
                          data-wow-delay="0.1s"
                        >
                          <div className="outer-box">
                            <div className="inner">
                              <div className="left-content">
                                <div className="icon-box">
                                  <span className="icon-writing" />
                                </div>
                                <div className="title-box">
                                  <h2>
                                    Optimal quality at <br />
                                    competitive prices.
                                  </h2>
                                </div>
                              </div>
                              <div className="right-content">
                                <p>
                                  Mestib ulligula remov project complete <br />
                                  marketing reserch to abusiness high process{" "}
                                </p>
                              </div>
                            </div>
                            <div className="overlay-content">
                              <div className="left-content">
                                <div className="number-box">01</div>
                                <div className="title-box2">
                                  <h2>
                                    Optimal quality at <br />
                                    competitive prices.
                                  </h2>
                                </div>
                              </div>
                              <div className="right-content">
                                <div className="btn-box">
                                  <a href="#">
                                    View Details{" "}
                                    <span className="icon-chevron" />
                                  </a>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
                        <li
                          className="wow animated fadeInRight"
                          data-wow-delay="0.3s"
                        >
                          <div className="outer-box">
                            <div className="inner">
                              <div className="left-content">
                                <div className="icon-box">
                                  <span className="icon-web-design" />
                                </div>
                                <div className="title-box">
                                  <h2>
                                    Ethical sourcing with
                                    <br />
                                    full transparency
                                  </h2>
                                </div>
                              </div>
                              <div className="right-content">
                                <p>
                                  Mestib ulligula remov project complete <br />
                                  marketing reserch to abusiness high process{" "}
                                </p>
                              </div>
                            </div>
                            <div className="overlay-content">
                              <div className="left-content">
                                <div className="number-box">02</div>
                                <div className="title-box2">
                                  <h2>
                                    Ethical sourcing with
                                    <br />
                                    full transparency
                                  </h2>
                                </div>
                              </div>
                              <div className="right-content">
                                <div className="btn-box">
                                  <a href="#">
                                    View Details{" "}
                                    <span className="icon-chevron" />
                                  </a>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
                        <li
                          className="wow animated fadeInRight"
                          data-wow-delay="0.3s"
                        >
                          <div className="outer-box">
                            <div className="inner">
                              <div className="left-content">
                                <div className="icon-box">
                                  <span className="icon-development" />
                                </div>
                                <div className="title-box">
                                  <h2>
                                    A strong brand image backed
                                    <br />
                                    by years of experience.
                                  </h2>
                                </div>
                              </div>
                              <div className="right-content">
                                <p>
                                  Mestib ulligula remov project complete <br />
                                  marketing reserch to abusiness high process{" "}
                                </p>
                              </div>
                            </div>
                            <div className="overlay-content">
                              <div className="left-content">
                                <div className="number-box">03</div>
                                <div className="title-box2">
                                  <h2>
                                    Website Design And <br />
                                    Development
                                  </h2>
                                </div>
                              </div>
                              <div className="right-content">
                                <div className="btn-box">
                                  <a href="#">
                                    View Details{" "}
                                    <span className="icon-chevron" />
                                  </a>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>
                  {/*End Services One Right Content*/}
                </div>
              </div>
            </section>
            {/*End Services One */}
            {/*Start Gallery One */}
            <section className="gallery-one">
              <div className="container">
                <div className="sec-title tg-heading-subheading animation-style2">
                  <div className="sec-title__tagline">
                    <p className="tg-element-title">Featured Products</p>
                    <div className="border-box" />
                  </div>
                  <h2 className="sec-title__title tg-element-title">
                    End to End Support
                  </h2>
                </div>
                <div className="row">
                  {/*Start Gallery One Single*/}
                  <div
                    className="col-xl-4 col-lg-6 col-md-6 wow fadeInLeft"
                    data-wow-delay="0ms"
                    data-wow-duration="1500ms"
                  >
                    <div className="gallery-one__single">
                      <div className="gallery-one__single-img">
                        <div className="inner">
                          <img src="assets/images/Container (1).png" alt="#" />
                          <div className="btn-box">
                            <a href="#">
                              <span className="icon-diagonal-arrow2" />
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/*End Gallery One Single*/}
                  {/*Start Gallery One Single*/}
                  <div
                    className="col-xl-4 col-lg-6 col-md-6 wow fadeInRight"
                    data-wow-delay="100ms"
                    data-wow-duration="1500ms"
                  >
                    <div className="gallery-one__single">
                      <div className="gallery-one__single-content">
                        <div className="number-box">01</div>
                        <h2>
                          <a href="#">Product Design</a>
                        </h2>
                        <p>
                          We design products from scratch to make sure your
                          customers get to experience the ultimate
                        </p>
                        <div className="btn-box">
                          <a href="#">
                            View Details <span className="icon-chevron" />
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/*End Gallery One Single*/}
                  {/*Start Gallery One Single*/}
                  <div
                    className="col-xl-4 col-lg-6 col-md-6 wow fadeInLeft"
                    data-wow-delay="200ms"
                    data-wow-duration="1500ms"
                  >
                    <div className="gallery-one__single">
                      <div className="gallery-one__single-img">
                        <div className="inner">
                          <img src="assets/images/support.png" alt="#" />
                          <div className="btn-box">
                            <a href="#">
                              <span className="icon-diagonal-arrow2" />
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/*End Gallery One Single*/}
                  {/*Start Gallery One Single*/}
                  <div
                    className="col-xl-4 col-lg-6 col-md-6 wow fadeInLeft"
                    data-wow-delay="0ms"
                    data-wow-duration="1500ms"
                  >
                    <div className="gallery-one__single">
                      <div className="gallery-one__single-img">
                        <div className="inner">
                          <img src="assets/images/Container (2).png" alt="#" />
                          <div className="btn-box">
                            <a href="#">
                              <span className="icon-diagonal-arrow2" />
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/*End Gallery One Single*/}
                  {/*Start Gallery One Single*/}
                  <div
                    className="col-xl-4 col-lg-6 col-md-6 wow fadeInRight"
                    data-wow-delay="100ms"
                    data-wow-duration="1500ms"
                  >
                    <div className="gallery-one__single">
                      <div className="gallery-one__single-content">
                        <div className="number-box">02</div>
                        <h2>
                          <a href="#">Sustainable Goods</a>
                        </h2>
                        <p>
                          We ensure each step in our process is ethically
                          sourced and sustainable.
                        </p>
                        <div className="btn-box">
                          <a href="#">
                            Download our brochure{" "}
                            <span className="icon-chevron" />
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/*End Gallery One Single*/}
                  {/*Start Gallery One Single*/}
                  <div
                    className="col-xl-4 col-lg-6 col-md-6 wow fadeInLeft"
                    data-wow-delay="200ms"
                    data-wow-duration="1500ms"
                  >
                    <div className="gallery-one__single">
                      <div className="gallery-one__single-img">
                        <div className="inner">
                          <img src="assets/images/support1.png" alt="#" />
                          <div className="btn-box">
                            <a href="#">
                              <span className="icon-diagonal-arrow2" />
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/*End Gallery One Single*/}
                </div>
              </div>
            </section>
            {/*End Gallery One */}

            {/*Start Testimonials One */}
         
            <section className="testimonials-one">
              <div className="container">
                <div className="testimonials-one__top">
                  <div className="sec-title tg-heading-subheading animation-style2">
                    <div className="sec-title__tagline">
                      <p className="tg-element-title">Testimonials</p>
                      <div className="border-box" />
                    </div>
                    <h2 className="sec-title__title tg-element-title">
                      Our Expert Clients
                    </h2>
                  </div>
                  <div className="btn-box">
                    <a className="thm-btn" href="contact.html">
                      <span className="txt">Client Feedback</span>
                      <span className="bdrl" />
                      <span className="bdrr" />
                    </a>
                  </div>
                </div>
                <div className="row">
                  <div className="col-xl-12">
                  <div>
  
      <TestimonialsCarousel />
    </div>



                  </div>
                </div>
              </div>
            </section>

            <section className="contact-page">
              <div className="container">
                <div className="row">
                  {/*Start Contact Page Map*/}
                  <div className="col-xl-5">
                    <div className="contact-page-google-map">
                      <iframe
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4562.753041141002!2d-118.80123790098536!3d34.152323469614075!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80e82469c2162619%3A0xba03efb7998eef6d!2sCostco+Wholesale!5e0!3m2!1sbn!2sbd!4v1562518641290!5m2!1sbn!2sbd"
                        className="contact-page-google-map__one"
                        allowFullScreen=""
                      />
                    </div>
                  </div>
                  {/*End Contact Page Map*/}
                  {/*Start Contact One Form*/}
                  <div className="col-xl-7">
                    <div className="contact-one__form">
                      <div className="sec-title tg-heading-subheading animation-style2">
                        <div className="sec-title__tagline">
                          <p className="tg-element-title">contact</p>
                          <div className="border-box" />
                        </div>
                        <h2 className="sec-title__title tg-element-title">
                          For Inquariy
                        </h2>
                      </div>
                      <form
                        id="contact-form"
                        className="default-form2 contact-form-validated"
                        action="https://unicktheme.com/baosh/assets/inc/sendemail.php"
                        noValidate="novalidate"
                      >
                        <div className="row">
                          <div className="col-xl-6 col-lg-6 col-md-6">
                            <div className="input-box">
                              <input
                                type="text"
                                name="name"
                                defaultValue=""
                                placeholder="NAME *"
                                required=""
                              />
                            </div>
                          </div>
                          <div className="col-xl-6 col-lg-6 col-md-6">
                            <div className="input-box">
                              <input
                                type="email"
                                name="email"
                                defaultValue=""
                                placeholder="EMAIL *"
                                required=""
                              />
                            </div>
                          </div>
                        </div>
                        <div className="row">
                          <div className="col-xl-6 col-lg-6 col-md-6">
                            <div className="input-box">
                              <input
                                type="text"
                                placeholder="PHONE *"
                                name="phone"
                              />
                            </div>
                          </div>
                          <div className="col-xl-6 col-lg-6 col-md-6">
                            <div className="input-box">
                              <input
                                type="text"
                                placeholder="SUBJECT *"
                                name="subject"
                              />
                            </div>
                          </div>
                        </div>
                        <div className="row">
                          <div className="col-xl-12">
                            <div className="input-box">
                              <textarea
                                name="message"
                                placeholder="WRITE YOUR MESSAGE *"
                                defaultValue={""}
                              />
                            </div>
                          </div>
                          <div className="col-xl-6 col-lg-6 col-md-6">
                            <div className="contact-one__form-btn">
                              <button
                                className="thm-btn"
                                type="submit"
                                data-loading-text="Please wait..."
                              >
                                <span className="txt">submit</span>
                                <span className="bdrl" />
                                <span className="bdrr" />
                              </button>
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                  {/*End Contact One Form*/}
                </div>
              </div>
            </section>
            {/*Start Slogan One */}
            <section className="slogan-one">
              <div className="auto-container">
                <div className="slogan-one__inner">
                  <div className="container">
                    <div className="slogan-one__content-box">
                      <div className="text-box tg-heading-subheading animation-style2">
                        <h2 className="tg-element-title">Get In Touch</h2>
                      </div>
                      <div className="btn-box">
                        <a className="thm-btn" href="contact.html">
                          <span className="txt">Send A Message</span>
                          <span className="bdrl" />
                          <span className="bdrr" />
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            {/*End Slogan One */}
            {/*Start Footer One */}
            <footer className="footer-one">
              {/*Start Footer*/}
              <div className="footer">
                <div className="container">
                  <div className="footer-one__inner">
                    <div className="logo-box text-center">
                      <a href="index.html">
                        <img src="assets/images/Mishael.png" alt="#" />
                      </a>
                    </div>
                    <div className="footer-one__contact">
                      <div
                        className="footer-one__contact-bdr"
                        style={{
                          backgroundImage:
                            "url(assets/images/footer/footer-v1-img1.png)",
                        }}
                      />
                      <ul>
                        <li>
                          <div className="icon-box">
                            <span className="icon-ringing" />
                          </div>
                          <div className="text-box">
                            <p>Call anytime</p>
                            <h3>
                              <a href="tel:98210009630">+ 9821 (000) - 9630</a>
                            </h3>
                          </div>
                        </li>
                        <li>
                          <div className="icon-box">
                            <span className="icon-message" />
                          </div>
                          <div className="text-box">
                            <p>Send email</p>
                            <h3>
                              <a href="mailto:yourmail@email.com">
                               mishael@company.com
                              </a>
                            </h3>
                          </div>
                        </li>
                        <li>
                          <div className="icon-box">
                            <span className="icon-placeholder" />
                          </div>
                          <div className="text-box">
                            <p>Visit Office</p>
                            <h3>27 Division St, New York</h3>
                          </div>
                        </li>
                      </ul>
                    </div>
                    <div className="footer-one__menu">
                      <ul>
                        <li>
                          <a href="#">Home</a>
                        </li>
                        <li>
                          <a href="#">Pages</a>
                        </li>
                        <li>
                          <a href="#">Services</a>
                        </li>
                        <li>
                          <a href="#">Home</a>
                        </li>
                      </ul>
                    </div>
                    <div className="footer-one__social-links">
                      <ul>
                        <li>
                          <a href="#">
                            <span className="icon-twitter" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <span className="icon-facebook" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <span className="icon-google-plus-logo" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <span className="icon-pinterest" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <span className="icon-wifi" />
                          </a>
                        </li>
                      </ul>
                      <div className="border-box" />
                    </div>
                    <div className="footer-one__copyright">
                      <p>
                        Copyright © 2024
                        <br />
                        all rights reserved.
                      </p>
                    </div>
                    <div className="scroll-to-top-box">
                      <a
                        href="#"
                        data-target="html"
                        className="scroll-to-target scroll-to-top"
                      >
                        Back to Top
                      </a>
                      <div className="border-box" />
                    </div>
                  </div>
                </div>
              </div>
              {/*End Footer*/}
            </footer>
            {/*End Footer One*/}
          </div>
          {/* /.page-wrapper */}
          <div className="mobile-nav__wrapper">
            <div className="mobile-nav__overlay mobile-nav__toggler" />
            <div className="mobile-nav__content">
              <span className="mobile-nav__close mobile-nav__toggler">
                <i className="icon-plus" />
              </span>
              <div className="logo-box">
                <a href="index.html" aria-label="logo image">
                  <img src="assets/images/Mishael.png" alt="" />
                </a>
              </div>
              <div className="mobile-nav__container" />
              <ul className="mobile-nav__contact list-unstyled">
                <li>
                  <i className="fa fa-envelope" />
                  <a href="mailto:info@example.com">info@example.com</a>
                </li>
                <li>
                  <i className="fa fa-phone-alt" />
                  <a href="tel:123456789">444 000 777 66</a>
                </li>
              </ul>
              <div className="mobile-nav__social">
                <a href="#" className="fab fa-twitter" />
                <a href="#" className="fab fa-facebook-square" />
                <a href="#" className="fab fa-pinterest-p" />
                <a href="#" className="fab fa-instagram" />
              </div>
            </div>
          </div>
          <div className="search-popup">
            <div className="search-popup__overlay search-toggler" />
            <div className="search-popup__content">
              <form action="#">
                <label htmlFor="search" className="sr-only">
                  search here
                </label>
                <input type="text" id="search" placeholder="Search Here..." />
                <button
                  type="submit"
                  aria-label="search submit"
                  className="thm-btn"
                >
                  <i className="icon-search-interface-symbol" />
                </button>
              </form>
            </div>
          </div>
        </>
      </main>
       

      <Scripts />
    </>
  );
}
